image: maven:3.6.3-openjdk-8-slim
ci_build:
  stage: build
  before_script:
#    - mkdir -p ~/.m2 && echo "${MVN_SETTINGS}" > ~/.m2/settings.xml
    - cat /etc/os-release
  script:
    - mvn clean package
