image: gitlab.rypox.pit:5050/rypox.org/gradle-image:latest

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - publish
  - release

build-job:
  stage: build
#  before_script:
#    - mkdir -p ~/.m2 && echo "${MVN_SETTINGS}" > ~/.m2/settings.xml
  script:
    - gradle --no-daemon build

publish-job:
  stage: publish
  script:
    - gradle --no-daemon publish

release-job:
  stage: release
  only:
    - tags
  script:
    - VERSION=${CI_COMMIT_TAG}
    - test -n "${VERSION}"
    - >-
      gradle 
      --no-daemon 
      -Pversion=${VERSION}
      publish
  artifacts:
    paths:
      - build/
    expire_in: 60 min
